# Conflict Gangs v0.0.1-dev#1 - Settings.yml configuration file
#
settings:
  # Implemented: JSON
  # TODO: MySQL, SQLite, YAML
  provier: json
  #
  # Saves startup time, remember to delete the cache after an update to the commands
  cach-command-data: true